backtest:
  atr_multiplier: 2.5
  cash: 10000.0
  commission: 0.0001
  conf_threshold: 0.44999999999999996
  margin: 0.02
  strategy: TripleBarrier
  v_size: 10000.0
data:
  atr_multipliers:
  - 1.0
  - 1.5
  - 2.0
  - 2.5
  - 3.0
  horizons:
  - 5
  - 12
  - 24
  lookback: 120
  processed_dir: data/processed_market
  raw_input: data/raw_market/EURUSD_H1_20210501_20260331.csv
  train_split_pct: 0.6
  val_split_pct: 0.2
model:
  batch_size: 64
  params:
    cnn_filters_1: 64
    cnn_filters_2: 128
    dropout: 0.30000000000000004
    epochs: 100
    kernel_size: 2
    learning_rate: 0.00011540782322836729
    lookback: 240
    lstm_units: 100
    weight_decay: 1.0786108839801087e-05
  target: Target_24h_2.5x_TBM
  type: CNN-LSTM
optimization:
  search_space:
    conf_threshold:
    - 0.35
    - 0.5
    - 0.05
    exit_atr_multiplier:
    - 1.0
    - 4.0
    - 0.5
project:
  name: forex-cnnlstm
  symbol: EURUSD
  timeframe: H1
